<a href="https://colab.research.google.com/github/PHAMTHUYDUYEN/E-wallet-Performance-Analysis-Python/blob/main/K27_Pham_Thuy_Duyen_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
payment_report = pd.read_csv("/content/payment_report.csv")
product = pd.read_csv("/content/product.csv")
transactions = pd.read_csv("/content/transactions.csv")

In [ ]:
payment_report.head()

  report_month payment_group  product_id  source_id     volume
0      2023-01       payment          12         45  624110375
1      2023-01       payment          17         45  335715113
2      2023-01       payment          18         45  737784466
3      2023-01       payment          19         45  120963069
4      2023-01       payment          20         45  319653158

In [ ]:
product.head()

   product_id category team_own
0          17  PXXXXXB      ASD
1          18  PXXXXXB      ASD
2          20  PXXXXXB      ASD
3         287  PXXXXXB      ASD
4         372  PXXXXXB      ASD

In [ ]:
transactions.head()

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp
0,3002692434,5,100000,24,1,10199794.0,199794.0,NaN,1682932054455
1,3002692437,305,20000,2,1,14022211.0,14022211.0,NaN,1682932054912
2,3001960110,7255,48605,22,1,NaN,10530940.0,NaN,1682932055000
3,3002680710,2270,1500000,2,1,10059206.0,59206.0,NaN,1682932055622
4,3002680713,2275,90000,2,1,10004711.0,4711.0,NaN,1682932056197

# **Part I: EDA**

## I.1. Missing Values

In [ ]:
print("---",payment_report.isna().sum())
print("---",product.isna().sum())
print("---",transactions.isna().sum())

--- report_month     0
payment_group    0
product_id       0
source_id        0
volume           0
dtype: int64
--- product_id    0
category      0
team_own      0
dtype: int64
--- transaction_id          0
merchant_id             0
volume                  0
transType               0
transStatus             0
sender_id           49059
receiver_id        164795
extra_info        1317907
timeStamp               0
dtype: int64

## I.2. Duplicates

In [ ]:
# Check if PK product_id has duplicates
print(product.shape)
print(product.nunique())

(492, 3)
product_id    492
category       17
team_own        3
dtype: int64

In [ ]:
# Check if PK transaction_id has duplicates
print(transactions.shape)
print(transactions.nunique())

(1324002, 9)
transaction_id    1323974
merchant_id           646
volume              49488
transType               7
transStatus            35
sender_id          173557
receiver_id        200291
extra_info           2037
timeStamp         1316590
dtype: int64

In [ ]:
# Check if transaction_id duplicates really duplicates
transactions[transactions.duplicated()]

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,extra_info,timeStamp
149735,3000871152,75,193000,2,1,1.702717e+07,NaN,NaN,1682988617608
149739,3000871161,2270,50000,2,1,1.000935e+07,9.352000e+03,NaN,1682988617770
149753,3000687030,2250,165000,8,1,1.007484e+07,3.854830e+07,NaN,1682988623437
149758,3000871242,2270,300000,2,1,3.501383e+07,3.501383e+07,NaN,1682988625523
149762,3000871251,5,200,22,1,1.002801e+07,1.052919e+07,NaN,1682988626225
251297,3000859278,60,50000,2,-217,1.752038e+07,1.752038e+07,NaN,1683075010868
251307,3000859287,75,19300,2,1,1.560510e+07,2.134597e+07,NaN,1683075013716
251345,3000853578,2895,25263,2,1,3.155863e+07,NaN,NaN,1683075020418
251349,3000853584,6140,21622,22,1,2.450001e+07,2.106593e+07,NaN,1683075020883
251353,3000853587,2270,500000,2,1,1.009376e+07,9.375800e+04,NaN,1683075021528
251355,3000871197,5,400,22,1,1.002801e+07,8.274000e+04,NaN,1683075021650
251360,3000669375,2250,100000,8,1,1.000116e+07,2.801112e+07,NaN,1683075022816
459826,3000859323,6140,7076,22,1,2.450001e+07,4.182500e+04,NaN,1683247817747
459832,3000847623,5,700,22,1,3.850001e+07,3.673782e+06,NaN,1683247820163
459838,3000847632,305,10000,2,1,1.053447e+07,5.344710e+05,NaN,1683247821222
459860,3000853623,8225,245027,2,1,1.014136e+07,NaN,NaN,1683247826214
459865,3000853635,305,10000,2,1,1.053503e+07,1.053503e+07,NaN,1683247826611
459868,3000853641,60,100000,2,1,1.000332e+07,3.318000e+03,NaN,1683247826899
565943,3000876186,2270,10000,2,1,1.424667e+07,4.246669e+06,NaN,1683420609231
565953,3000675189,2250,6000,8,1,1.003888e+07,2.101640e+07,NaN,1683420610712
565971,3000859380,305,100000,2,1,1.702837e+07,7.028371e+06,NaN,1683420625775
565975,3000859386,75,48250,2,1,4.368219e+09,1.456485e+09,NaN,1683420626895
837468,3000859308,2250,20000,8,1,3.153879e+07,2.522800e+04,NaN,1683161415206
837472,3000859314,305,100000,2,1,1.023464e+07,2.346400e+05,NaN,1683161416065
1045769,3000876015,745,100000,30,1,NaN,3.726342e+09,NaN,1682902183161
1045881,3000871119,7010,5900,2,1,1.050709e+07,1.050709e+07,NaN,1682902213719
1045907,3000876303,5,300,22,1,1.002801e+07,3.155114e+07,NaN,1682902224983
1045916,3000876327,5,200,22,1,1.002801e+07,2.586542e+06,NaN,1682902226938

In [ ]:
# Drop duplicates in Transactions df
transactions.drop_duplicates(inplace = True)
print(transactions.shape)
print(transactions.nunique())

(1323974, 9)
transaction_id    1323974
merchant_id           646
volume              49488
transType               7
transStatus            35
sender_id          173557
receiver_id        200291
extra_info           2037
timeStamp         1316590
dtype: int64

## I.3. Data Types

In [ ]:
# Check data types of 3 tables
print(payment_report.info())
print(product.info())
print(transactions.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 919 entries, 0 to 918
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   report_month   919 non-null    object
 1   payment_group  919 non-null    object
 2   product_id     919 non-null    int64
 3   source_id      919 non-null    int64
 4   volume         919 non-null    int64
dtypes: int64(3), object(2)
memory usage: 36.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 492 entries, 0 to 491
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  492 non-null    int64
 1   category    492 non-null    object
 2   team_own    492 non-null    object
dtypes: int64(1), object(2)
memory usage: 11.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
Index: 1323974 entries, 0 to 1324001
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   transaction_id  1323974 non-null  int64
 1   merchant_id     1323974 non-null  int64
 2   volume          1323974 non-null  int64
 3   transType       1323974 non-null  int64
 4   transStatus     1323974 non-null  int64
 5   sender_id       1274916 non-null  float64
 6   receiver_id     1159182 non-null  float64
 7   extra_info      6095 non-null     object
 8   timeStamp       1323974 non-null  int64
dtypes: float64(2), int64(6), object(1)
memory usage: 101.0+ MB
None

## I.4. Data Values

In [ ]:
print(payment_report.describe())
print(product.describe())
print(transactions.describe())

         product_id   source_id        volume
count    919.000000  919.000000  9.190000e+02
mean    1192.517954   44.875952  1.978574e+08
std     1293.463329    0.910995  8.367595e+08
min        3.000000   37.000000  5.500000e+03
25%      640.000000   45.000000  1.250000e+06
50%     1059.000000   45.000000  7.982015e+06
75%     1585.000000   45.000000  5.447599e+07
max    15067.000000   45.000000  1.383171e+10
         product_id
count    492.000000
mean     862.886179
std     1015.964776
min        9.000000
25%      270.750000
50%      616.500000
75%     1419.250000
max    15067.000000
       transaction_id   merchant_id        volume     transType   transStatus  \
count    1.323974e+06  1.323974e+06  1.323974e+06  1.323974e+06  1.323974e+06
mean     3.002234e+09  2.460332e+03  2.388093e+05  6.979182e+00 -1.204636e+01
std      1.042617e+07  3.304293e+03  9.681107e+05  7.459665e+00  5.577851e+01
min      3.000000e+09  5.000000e+00  1.000000e+00  2.000000e+00 -1.333000e+03
25%      3.001121e+09  3.050000e+02  1.000000e+04  2.000000e+00  1.000000e+00
50%      3.002200e+09  2.250000e+03  3.000000e+04  2.000000e+00  1.000000e+00
75%      3.003255e+09  2.270000e+03  1.000000e+05  8.000000e+00  1.000000e+00
max      6.000066e+09  1.625250e+05  7.869148e+07  3.000000e+01  1.000000e+00

          sender_id   receiver_id     timeStamp
count  1.274916e+06  1.159182e+06  1.323974e+06
mean   1.033922e+08  2.084882e+08  1.683130e+12
std    6.234255e+08  9.287825e+08  1.707816e+08
min    1.000001e+07 -6.300000e+01  1.682874e+12
25%    1.005657e+07  1.526700e+05  1.682994e+12
50%    1.094200e+07  7.025130e+06  1.683097e+12
75%    2.101266e+07  3.151238e+07  1.683269e+12
max    6.993439e+09  2.100000e+10  1.683479e+12

In [ ]:
# Convert receiver_id to positive
transactions["receiver_id"] = np.abs(transactions["receiver_id"])
transactions.describe()

,transaction_id,merchant_id,volume,transType,transStatus,sender_id,receiver_id,timeStamp
count,1.323974e+06,1.323974e+06,1.323974e+06,1.323974e+06,1.323974e+06,1.274916e+06,1.159182e+06,1.323974e+06
mean,3.002234e+09,2.460332e+03,2.388093e+05,6.979182e+00,-1.204636e+01,1.033922e+08,2.084882e+08,1.683130e+12
std,1.042617e+07,3.304293e+03,9.681107e+05,7.459665e+00,5.577851e+01,6.234255e+08,9.287825e+08,1.707816e+08
min,3.000000e+09,5.000000e+00,1.000000e+00,2.000000e+00,-1.333000e+03,1.000001e+07,0.000000e+00,1.682874e+12
25%,3.001121e+09,3.050000e+02,1.000000e+04,2.000000e+00,1.000000e+00,1.005657e+07,1.526700e+05,1.682994e+12
50%,3.002200e+09,2.250000e+03,3.000000e+04,2.000000e+00,1.000000e+00,1.094200e+07,7.025130e+06,1.683097e+12
75%,3.003255e+09,2.270000e+03,1.000000e+05,8.000000e+00,1.000000e+00,2.101266e+07,3.151238e+07,1.683269e+12
max,6.000066e+09,1.625250e+05,7.869148e+07,3.000000e+01,1.000000e+00,6.993439e+09,2.100000e+10,1.683479e+12

## I.5. EDA Summary

1. Missing data: \
In Transactions table:\
42183 rows in sender_id -> No base to fill in -> No action\
138933 rows in receiver_id -> No base to fill in -> No action\
1130449 rows in extra_info -> No action

2. Duplicates:\
In PK transaction_id of Transactions table:\
28 duplicated rows -> Delete rows

3. Incorrect data types: \
All data types are correct

4. Incorrect values: \
In Transactions table:\
receiver_id has negative values -> Convert all to positive\
transStatus has negative values -> Don’t understand meaning -> No action

# **Part II: Data Wrangling**

## II.1. Merge payment_report df with product df

In [ ]:
payment_enriched = pd.merge(payment_report, product, on="product_id", how="outer")
payment_enriched.head()

,report_month,payment_group,product_id,source_id,volume,category,team_own
0,2023-01,payment,12,45.0,624110375.0,PXXXXXT,ASD
1,2023-02,payment,12,45.0,525812529.0,PXXXXXT,ASD
2,2023-03,payment,12,45.0,405504433.0,PXXXXXT,ASD
3,2023-04,payment,12,45.0,379013493.0,PXXXXXT,ASD
4,2023-01,payment,17,45.0,335715113.0,PXXXXXB,ASD

## Q1: Top 3 product_ids with the highest volume.

In [ ]:
volume_by_product = payment_enriched.groupby("product_id")["volume"].sum()
volume_by_product.nlargest(3)

product_id
1976    6.179758e+10
429     1.466768e+10
372     1.371366e+10
Name: volume, dtype: float64

## Q2: Given that 1 product_id is only owed by 1 team, are there any abnormal products against this rule?

In [ ]:
team_by_product = payment_enriched.groupby("product_id").agg({"team_own":"count"})
team_by_product[team_by_product["team_own"] != 1]

            team_own
product_id
3                  0
12                 4
15                 2
17                 4
18                 4
...              ...
2356               3
2587               2
10033              0
10039              4
15067              3

[237 rows x 1 columns]

## Q3: Find the team had the lowest performance (lowest volume) since Q2.2023. Find the category that contributes the least to that team.

In [ ]:
# Filter values in Q2.2023
q2_2023 = payment_enriched[payment_enriched["report_month"].isin(["2023-04","2023-05","2023-06"])]

# Calculate volume by team
volume_by_team = q2_2023.groupby("team_own").agg({"volume":"sum"})

# Identify lowest performance team
volume_by_team["volume"].nsmallest(1)

team_own
APS    51141753.0
Name: volume, dtype: float64

In [ ]:
# Filter values of ... team
aps = payment_enriched[payment_enriched["team_own"] == "APS"]

# Calculate volume by category
volume_by_category = aps.groupby("category").agg({"volume":"sum"})

# Identify lowest contributed category
volume_by_category["volume"].nsmallest(1)

category
PXXXXXO    0.0
Name: volume, dtype: float64

## Q4: Find the contribution of source_ids of refund transactions (payment_group = ‘refund’), what is the source_id with the highest contribution?

In [ ]:
# Filter 'refund' payment group
refund = payment_enriched[payment_enriched["payment_group"] == "refund"]

# Calculate volume by source_id
volume_by_souce = refund.groupby("source_id").agg({"volume":"sum"})

# Identify source_id having highest volume
volume_by_souce["volume"].nlargest(1)

source_id
38.0    3.652745e+10
Name: volume, dtype: float64

## Q5: Define type of transactions (‘transaction_type’) for each row, given:
- transType = 2 & merchant_id = 1205: Bank Transfer Transaction
- transType = 2 & merchant_id = 2260: Withdraw Money Transaction
- transType = 2 & merchant_id = 2270: Top Up Money Transaction
- transType = 2 & others merchant_id: Payment Transaction
- transType = 8, merchant_id = 2250: Transfer Money Transaction
- transType = 8 & others merchant_id: Split Bill Transaction
- Remained cases are invalid transactions

In [ ]:
# Create list of Transaction type
transaction_category = ["Bank Transfer Transaction", "Withdraw Money Transaction", "Top Up Money Transaction", "Payment Transaction", "Transfer Money Transaction", "Split Bill Transaction"]

# Create list of Conditions
conditions = [
              ((transactions["transType"]==2)&(transactions["merchant_id"]==1205)),
              ((transactions["transType"]==2)&(transactions["merchant_id"]==2260)),
              ((transactions["transType"]==2)&(transactions["merchant_id"]==2270)),
              (transactions["transType"]==2),
              ((transactions["transType"]==8)&(transactions["merchant_id"]==2250)),
              (transactions["transType"]==8)
              ]

# Create new column 'transaction_type'
transactions["transaction_type"] = np.select(conditions, transaction_category, default="Invalid Transaction")

print(transactions.head())

   transaction_id  merchant_id   volume  transType  transStatus   sender_id  \
0      3002692434            5   100000         24            1  10199794.0
1      3002692437          305    20000          2            1  14022211.0
2      3001960110         7255    48605         22            1         NaN
3      3002680710         2270  1500000          2            1  10059206.0
4      3002680713         2275    90000          2            1  10004711.0

   receiver_id extra_info      timeStamp          transaction_type
0     199794.0        NaN  1682932054455       Invalid Transaction
1   14022211.0        NaN  1682932054912       Payment Transaction
2   10530940.0        NaN  1682932055000       Invalid Transaction
3      59206.0        NaN  1682932055622  Top Up Money Transaction
4       4711.0        NaN  1682932056197       Payment Transaction

## Q6: Of each transaction type (excluding invalid transactions): find the number of transactions, volume, senders and receivers.

In [ ]:
# Count transaction, volume, senders, receivers of each transaction type
grouped_rs_transaction = transactions.groupby("transaction_type").agg(
                                    transaction_count=("transaction_id","count"),
                                    volume_count=("volume","count"),
                                    sender_count=("sender_id","count"),
                                    receiver_count=("receiver_id","count")
                                  ).reset_index()

# Exclude invalid transactions
grouped_rs_transaction[grouped_rs_transaction["transaction_type"] != "Invalid Transaction"].reset_index(drop=True)

,transaction_type,transaction_count,volume_count,sender_count,receiver_count
0,Bank Transfer Transaction,37879,37879,37879,14004
1,Payment Transaction,398665,398665,398665,259982
2,Split Bill Transaction,1376,1376,1376,1376
3,Top Up Money Transaction,290498,290498,290498,290498
4,Transfer Money Transaction,341173,341173,341173,341173
5,Withdraw Money Transaction,33725,33725,33725,33725